### ISSUE TITLE
Force Close on API level >= 26

### ISSUE THREAD

**Issue by Amerlander** [NordicSemiconductor/Android-nRF-Blinky#10]
The App closes immediately after the start on devices running android Oreo.
Tested on Xiaomi Mi5 (runed well before Update) and in Emulator.

**Comment by philips77** [comment]
Hi, 
Thanks, I'll check it when I get back from vacations.

**Comment by watson-yu** [comment]
Disabled InstantRun and it runs fine on my Pixel2 / Android 8.1.0.
Ref:https://stackoverflow.com/questions/49508571/android-studio-3-1-error-while-compile
