### ISSUE TITLE
Latest version is not working correctly.

### ISSUE THREAD

**Issue by devangichhatbar** [NordicSemiconductor/Android-nRF-Blinky#18]
**Scanner screen is continuously scanning. But did not able to scan device.** 

Here I am attaching screenshot. I can't able to move from this screen.
![screenshot_20181115-114102](https://user-images.githubusercontent.com/13677061/48533688-7a243b00-e8cb-11e8-8032-52e735c82ce9.png)

**Comment by philips77** [comment]
HI, I've just tested the app from Play Store and it works for me. Do you see your device using nRF Connect? Do you have Location enabled?

**Comment by devangichhatbar** [comment]
Yes. I see my device using nRF connect. Yes, Location is enabled.

**Comment by philips77** [comment]
Is it advertising with `00001523-1212-efde-1523-785feabcd123` service UUID?

**Comment by devangichhatbar** [comment]
No, I am using my own device service UUID.

**Comment by philips77** [comment]
That's why it's not visible. nRF Blinky filters only for this UUID. You may clone the project from GitHub and modify to match your needs.

**Comment by philips77** [comment]
The Play Store version is expecting the UUIDs provided above in device's advertising packets. You may try emulating Blinky sample with nRF Connect on another phone and adding the Blinky Service UUID into the advertisement.

**Comment by Pareshoct7** [comment]
Yes, Similar kind of issue. But I just install app from play store and then try to connect. And It is perfectly working with nRF connect. But not with nRF Blinky.

**Comment by philips77** [comment]
Do you see your device in nRF Blinky? Check in nRF Connec if it is advertising with Blinky UUID. The nRF Blinky app filters only this UUID.

**Comment by Pareshoct7** [comment]
How can I customize with my device? Where I have to change the UUID?

**Comment by philips77** [comment]
Hi, I thought it will be easiest when I release the new version with scanner filters. Now, using the menu, you may deselect requirement for UUID and all devices in range will be shown. However, Blinky Service ( aka LBS, Led-Button Service) is still required after connection. The new version, 2.4.0, is available now on GitHub and in few moments on Google Play.

**Comment by philips77** [comment]
Hi, did the new version fix your problem?
