### ISSUE TITLE
NRF51 Firmware

### ISSUE THREAD

**Issue by mahbubiftekhar** [NordicSemiconductor/Android-nRF-Blinky#21]
Hi

Is the original files for creating the hex available? 

https://github.com/NordicSemiconductor/Android-nRF-Blinky/tree/master/Firmwares/nRF51_SDK11.0.0

Thanks,

**Comment by philips77** [comment]
You'll find it here: https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v11.x.x/. For new projects we recommend using SDK 15.2 for nrf52 or sdk 12.2 for nrf51.

**Comment by mahbubiftekhar** [comment]
Thanks! Appreciate your help :+1:
