### ISSUE TITLE
How to fix switch LED?

### ISSUE THREAD

**Issue by ArTyGill** [NordicSemiconductor/Android-nRF-Blinky#26]
In the latest version of Blinky, the LED turns on, but does not allow it to be turned off.

**Comment by ArTyGill** [comment]
Solved the problem by deleting 188 and 189 lines in the file "BlinkyManager.java" .

https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/profile/BlinkyManager.java

**Comment by ArTyGill** [comment]
How can I fix the problem on the controller so that the application works out of the box?

**Comment by philips77** [comment]
Doesn't it work out of the box with the unmodified Blinky sample from the sdk?

**Comment by ArTyGill** [comment]
I use esp32 as a controller and I wrote the firmware on it myself, everything was fine, but with the latest version of the Nrf Blinky I can turn on and can not turn off the LED. Without correction in the code of one line.

**Comment by ArTyGill** [comment]
I get a warning "Invalid data received: ", possible with this problem. And it prevents me from receiving a callback  onLedStateChanged.
What is the callback onLedStateChanged? What is this callback for?

**Comment by ArTyGill** [comment]
Now everything is rebuilt and it seems to work. Sources work.
