### ISSUE TITLE
Lost words when sent by bluetooth.

### ISSUE THREAD

**Issue by ArTyGill** [NordicSemiconductor/Android-nRF-Blinky#27]
When sending messages with a length of more than 30 characters( the Mtu is set to 512) to any of the characteristics, the messages sometimes do not reach completely, but at the same time everything works well in the NRF CONNECT, the Mtu is set to 512.

**Comment by roshanrajaratnam** [comment]
@ArTyGill I guess this issue does not belong here in this repo. Please create an issue on the relevant nRF Connect for [Android](https://github.com/NordicSemiconductor/Android-nRF-Connect)  or [iOS](https://github.com/NordicSemiconductor/IOS-nRF-Connect)
