### ISSUE TITLE
Remove the scanning for the particualr UUID filter.

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Blinky#34]
Hi in this project i want to remove the scanning for the particular service or UUID.
i want to scan for all the Devices.( if Connection not working also is fine with me.)
On opening of the application i want to scan for all the devies and show them in the List.

how to achieve this feature in the application..?

**Comment by roshanrajaratnam** [comment]
@VinayTShetty you may change this in the settings in the app. If you are making changes to the app just  set `filterByUuid(final boolean uuidRequired)` to false.
