### ISSUE TITLE
Use BlinkyManager Singleton in Viewmodel

### ISSUE THREAD

**Issue by zawawimanja** [NordicSemiconductor/Android-nRF-Blinky#37]
I have modified this project by adding a NewActivity file and also a button in BlinkyActivity. When the user clicks the button will navigate to NewActivity.

A and B situation will refer to the same example below.

A - mBlinkyManager = new BleRepository(getApplication());

B - 	mBlinkyManager =  BleRepository.getBlinkyManager(getApplication());

1 .E/BleManager: onMtuChanged error & Connection 

a ) The problem when using your example is E/BleManager: onMtuChanged error: 4, mtu: 247. This time when instantiating the object in the ViewModel the connection is stable. It will not disconnected automatically.

b) The problem when using singleton only is E/BleManager: onMtuChanged error: 4, mtu and sometimes the connection is not stable. It will be lost then it will disconnected automatically.

2. Back pressed from NewActivity to BlinkyActivty

a) When back pressed the LED1 is still yellow light. It means the connection still there.

b) When back pressed the LED1 will turn to blink yellow light. It means the connection already disconnected automatically.

3. So how to solve my problem regarding the   E/BleManager: onMtuChanged error:  ??

**Comment by roshanrajaratnam** [comment]
Hi, I would suggest creating your repository as a Singleton instead of the BlinkyManager and create your BlinkyManager instance in the repository. Basically move the connection establishment to the repository from the ViewModel. This would let you access the same BlinkyInstance from the BleRepository and observe the connection states from almost any activity.

**Comment by zawawimanja** [comment]
Hi , Actually I have  replaced BlinkyManager as BlinkyRepository. Then in
ViewModel I am  calling the singleton BlinkRepository but failed.

Or what you means is to create other file name Repository. Then in
repository , instantiate the BlinkyManager in Repository. Instantiate the
Repository as Singleton and call it in ViewModel ?So I have 2 files for
doing this  BlinkyManager and Repository  compare above method only
requires  1 files only Repository.

**Comment by roshanrajaratnam** [comment]
I don't think having two class files here will make major impact. This is more easier to deal with in your case having one BlinkyManager instance in your BlinkyRespository and having all your viewmodels access the same manager that handles the connections. hope this helps.
