### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Blinky#4]
### ![screenshot1](https://user-images.githubusercontent.com/33421892/34639171-7bbed1b2-f300-11e7-8273-b3a191850648.PNG)
![screenshot2](https://user-images.githubusercontent.com/33421892/34639172-7be6343c-f300-11e7-85b4-97b7acba3a99.PNG)

![build gradle_moduleapp1](https://user-images.githubusercontent.com/33421892/34639168-6b3b4712-f300-11e7-9c3f-0b3911913e7b.PNG)
![build gradle_moduleapp2](https://user-images.githubusercontent.com/33421892/34639169-6b6545d0-f300-11e7-947d-1b0c30581e15.PNG)

![build gradle](https://user-images.githubusercontent.com/33421892/34639167-6562cb58-f300-11e7-81d2-0220026f85b7.PNG)
**Its showing few errors after opening in android Studio.Can u guide on Resolving it.**
![androidstudio_screenshot](https://user-images.githubusercontent.com/33421892/34639160-590bf3e8-f300-11e7-8b7b-3dcaa95e880c.PNG)

**Comment by philips77** [comment]
Try pulling latest changes in BLE library project and syncing again. I added the ble.iml to github there so importing the library first as a standalone project should not be required anymore.

**Comment by rajnishkumar9250** [comment]
@philips77 : I just clone it, giving same error. Please check once again

**Comment by rajnishkumar9250** [comment]
@philips77  as follow step 1, there is no build option for this library project.  I think because it is iml file only. I followed step 2 as well. Its correct what u said . still i m facing the same issue.

**Comment by dohoangminhquan** [comment]
I have the same issue. Do we have a solution for this ? I can compile BLE.

**Comment by philips77** [comment]
Check if the path to the BLE module in settings.gradle file is correct.

**Comment by dohoangminhquan** [comment]
All is correct...

**Comment by dohoangminhquan** [comment]
It happens with both DFU and BLE

**Comment by philips77** [comment]
DFU lib can be added with jcenter dependency.
Could you share what error you get now with nRF Blinky and BLE Library?

**Comment by dohoangminhquan** [comment]
in my settings:

include ':app', ':smsmms', ':ExpandableLayout',':libVerrooCore',':libVerrooAndroidBle',':ble',':dfu'

project (':libVerrooCore').projectDir = new File('../rmd-libVerrooCoreJava')
project (':libVerrooAndroidBle').projectDir = new File('../rmd-libVerrooAndroidBle')
project (':ble').projectDir = new File('../Android-BLE-Library')
project (':dfu').projectDir = new File('../Android-DFU-Library')

in my build:
    implementation project(':smsmms')
    implementation project(':ExpandableLayout')
    implementation project(':libVerrooCore')
    implementation project(':libVerrooAndroidBle')
    implementation project(':ble')
    implementation project(':dfu')

And the error I have:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :ble.
(many errors like this for both dfu and ble)

Only ble and dfu have trouble. other modules are fine.

**Comment by philips77** [comment]
You have path to the project, not to the module.
"/ble" and "/dfu" is missing in the paths.
Check out this https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/settings.gradle

**Comment by dohoangminhquan** [comment]
Thanks, I checked the guide and it works.

**Comment by philips77** [comment]
Could you paste a screenshot of your projects folder hierarchy?

**Comment by philips77** [comment]
Since version 2.1.0 the app is now using jcenter to import the BLE library dependency.
See bb41ddbe5e0277f16b89a28b46e5b94132ad3a75.

**Comment by VinayTShetty** [comment]
Can please explain via some screenshots.
And post it on issues..

So everyone will be able to resolve it and solve the issue..

Actually what your saying it's confusing.

**Comment by philips77** [comment]
You no longer need the Android BLE Library project. Pull recent changes on nRF Blinky project and build it. The BleManager is now imported as a dependency in build.gradle file. No more issues and unslept nights.

**Comment by philips77** [comment]
Hi, sorry, but we are not using firebase and have no experience with it. Also, your issue is not related to nRF Blinky. Please, ask on firebase forums, I'm sure someone has already solve it.
