### ISSUE TITLE
no.nordicsemi.android.blinky.databinding does not exist ？

### ISSUE THREAD

**Issue by xhtlxa** [NordicSemiconductor/Android-nRF-Blinky#46]
Import project tips，no.nordicsemi.android.blinky.databinding does not exist

**Comment by philips77** [comment]
This package is generated automatically with this setting:
https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/f27a78e20068b2e54e8f2701c7c2f5c52c412c3c/app/build.gradle#L28-L30
