### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by xhtlxa** [NordicSemiconductor/Android-nRF-Blinky#47]
Hi! Can this demo only connect to your equipment?

**Comment by roshanrajaratnam** [comment]
This can connect to a nRF Devkit  flashed with the the Nordic Led Button Service example provided in the nRF5 SDK.

**Comment by xhtlxa** [comment]
Is there a way to connect other devices? Or is there a demo for connecting other devices?

**Comment by roshanrajaratnam** [comment]
What are these other devices you are referring to? You may change the UUID in the BLE manager so that you can connect to other examples provided by Nordic. Please refer to the Readme.

**Comment by xhtlxa** [comment]
好的，谢谢

**Comment by xhtlxa** [comment]
Okay thank you
