### ISSUE TITLE
How to connect two nordic device at same time and receive callbacks

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [NordicSemiconductor/Android-nRF-Blinky#50]
How to connect two NRF Development Kit at same time with the mobile and send and receive led and button callbacks in it

**Comment by philips77** [comment]
If you're using Android BLE Library, you need 2 instances of `BleManager`. One for each connected device. Android should handle up to 6 or perhaps more simultaneous connections, perhaps depending on the connection parameters.
