### ISSUE TITLE
cannot find symbol class Request

### ISSUE THREAD

**Issue by PawelKaniewski** [NordicSemiconductor/Android-nRF-Blinky#6]
I cannot compile this project because of that error
![gitscreen](https://user-images.githubusercontent.com/39535553/40386071-03625814-5e09-11e8-8158-74149a7bca3c.png)
I have almost the same problem with nRF-Toolbox.
I have dowloaded the BLE library. I also checked that on other computer.
Could you please help me?

**Comment by philips77** [comment]
Hi, that's because the BLE Library has been updated, but this project not yet. Just import the Request class from the same packet as BleManager. I'll fix the project tomorrow.
Thanks for the bug report!

**Comment by philips77** [comment]
Fixed with version 2.1.0.
