### ISSUE TITLE
How to parse custom manufacturer data?

### ISSUE THREAD

**Issue by licoba** [NordicSemiconductor/Android-nRF-Blinky#82]
There are a lot of customized data in my broadcast data,
Such as power, mac address, version, and so on,
Where is the best place to create parsing code and module code for parsing classes,
Can you provide an example? Thanks.

**Comment by philips77** [comment]
Hello,
Are you planning to modify nRF Blinky app? 

If you want to modify how the device view looks like, or add more data there, you may set custom `deviceItem` using
https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/506cabe8884364cd4302cc490664ec020c42728b/scanner/src/main/java/no/nordicsemi/android/scanner/ScannerView.kt#L63-L70

In the lambda the parameter contains all scanned advertising data.
